### ISSUE TITLE
LV1 To-Do List review from gunhoray

### ISSUE THREAD

**Issue by gunhoray** [makepin2r/hh99_react_todolist#2]
코드를 리뷰하며 느낀점…

1. 각각의 기능들을 구현하며 나와는 다른 Javascript 문법으로 생긴 로직들이 너무 신기했습니다. 
: item의 id값을 주는 방식 (++nextID) (본인은 .length +1 활용, 배열 속의 요소가 삭제로 인해 사라지면, 남아있는 요소들의 고유의 값이여야하는 id값이 변형 된다는 것을 배울 수 있었다.)
: 객체 배열의 불변성을 지키기 위해 .concat 활용 (본인은 spread operator 활용, 둘중 어떤 것이 더 빠르고 좋은가?)
: TodoItem에 있는 deleteFunc(removeTodo 호출)와 toggleFunc(toggleTodo호출)를 이용, isDone의 boolean 타입 값을 활용한 심플한 toogle 방식. (본인은 id값을 매개변수로 받아오며 find, filter 활용)
: html의 form, onSubmit, placeholder, classtype, type, text 활용  
: <Button /> 안에서 삼항 연산자를 쓰며, classType과 text에 변화를 준 것. (본인은 button의 onClick={function}만 활용)
: TodoInput에서 form onSubmit을 활용하여 preventDefault(새로고침방지) & insertTodo 값 넣어주기 & 인풋초기화를 설정. insertTodo 함수를 매개변수로 받아오며 submitTodo에서 insertTodo에 값을 넣어주는 방식.

2. 컴포넌트 분리가 세세하게 되어 있는 부분이 좋았다.
In App : App.css & Template & TodoList & TodoInput & React, {useState}를 import / App을 export
    : in Template : Template.css & React를 import / Template을 export
   : in TodoList : TodoList.css & TodoItem & React를 import / TodoList을 export
             -> : in TodoItem : TodoItem.css & Button & React를 import / TodoItem을 export
    : in TodoInput : TodoInput.css & Button & React, {useState}를 import / TodoInput을 export
             -> : in Button : Button.css & React를 import / Button을 export

3. Button.jsx와 관련된 4가지의 parameter가 들어오는 구조에서 특정 버튼을 쓰는 상황에 따라 활용되는 파라미터가 달라지며, onClick과 type 둘중 하나가 undefined 되는 컴포넌트의 구조가 적절한 설계인가?
: 시간복잡도 / 공간복잡도를 계산하는 방법을 정확히 알고 있으면 답을 드릴 수 있을 것 같습니다. 작성된 코드가 최선의 코드인지 변별해내는 방법을 저도 공부해야 할 것 같습니다.
: 개인적으로 실행을 하는 것에 문제도 없으니 컴포넌트 분리가 잘 되었다는 것을 보여주는 것 같습니다. 좋은 설계인 것 같습니다.

**Comment by makepin2r** [comment]
정성어린 리뷰 감사합니다! 😆
